### ISSUE TITLE
EmbeddingSimilarity cause 'NoneType' object has no attribute '_inbound_nodes'

### ISSUE THREAD

**Issue by Atakey** [CyberZHG/keras-bert#119]
I want to implement a model that should use EmbeddingSimilarity ,but it caused 'NoneType' object has no attribute '_inbound_nodes'.
I create a simple example:
`
```
import keras.backend as K
from keras import Input, Model, losses
from keras.layers import Embedding
from keras.optimizers import SGD

from BERT.transformer import EmbeddingSimilarity

if __name__ == "__main__":
    input = Input(shape=(256,))
    word_Embedding = Embedding(1024, 256, input_length=256,
                               mask_zero=False, trainable=True,
                               name="Embedding-word")
    input_embedding = word_Embedding(input)
    embed_weights = K.identity(word_Embedding.embeddings)
    mlm_pred_layer = EmbeddingSimilarity(name='MLM-Sim')([input_embedding, embed_weights])

    model = Model(inputs=input, outputs=mlm_pred_layer)
    model.compile(optimizer=SGD(), loss=losses.sparse_categorical_crossentropy)
```
`
Error information:
````
Using TensorFlow backend.
WARNING:tensorflow:From G:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "G:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3ba785bf2396>", line 1, in <module>
    runfile('G:/JupyterWorkSpace/InfosExtractor/code/BERT/AttrTest.py', wdir='G:/JupyterWorkSpace/InfosExtractor/code/BERT')
  File "G:\PyCharm\PyCharm 2018.3.4\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "G:\PyCharm\PyCharm 2018.3.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/JupyterWorkSpace/InfosExtractor/code/BERT/AttrTest.py", line 17, in <module>
    model = Model(inputs=input, outputs=mlm_pred_layer)
  File "G:\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "G:\Anaconda3\lib\site-packages\keras\engine\network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "G:\Anaconda3\lib\site-packages\keras\engine\network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "G:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1366, in _map_graph_network
    tensor_index=tensor_index)
  File "G:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1353, in build_map
    node_index, tensor_index)
  File "G:\Anaconda3\lib\site-packages\keras\engine\network.py", line 1325, in build_map
    node = layer._inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'
````

keras==2.2.4
tf ==1.13.1

**Comment by Atakey** [comment]
I should wrap K.identity(...) into Lambda layer. That solve my problem.
