### ISSUE TITLE
bert model could not applied in TimeDistributed wrapper.

### ISSUE THREAD

**Issue by phoenixkillerli** [CyberZHG/keras-bert#144]
**Describe the Bug**
modified test code, got error:
```python
AssertionError: Could not compute output Tensor("lambda_1/strided_slice:0", shape=(?, 768), dtype=float32)
```

bert model could not applied in TimeDistributed wrapper.

**Version Info**

*tensorflow 1.12
*keras 2.2.4

**Minimal Codes To Reproduce**

```python
from keras_bert import load_trained_model_from_checkpoint, Tokenizer
from keras.layers import *
from keras.models import Model

config_path = './chinese_L-12_H-768_A-12/bert_config.json'
checkpoint_path = './chinese_L-12_H-768_A-12/bert_model.ckpt'
dict_path = './chinese_L-12_H-768_A-12/vocab.txt'

bert_model = load_trained_model_from_checkpoint(config_path,
                                                checkpoint_path,
                                                seq_len=None)

for l in bert_model.layers:
    l.trainable = True

MAX_SENTENCE_LENGTH = 128
MAX_SENTENCE_COUNT = 64
l2_reg = regularizers.l2(1e-8)
n_classes = 2

x1 = Input(shape=(MAX_SENTENCE_LENGTH, ), dtype='int32')
x2 = Input(shape=(MAX_SENTENCE_LENGTH, ), dtype='int32')
sentence = bert_model([x1, x2])
sentence = Lambda(lambda x: x[:, 0])(sentence)
temp = Model([x1, x2], sentence)
texts_in = Input(shape=(MAX_SENTENCE_COUNT, MAX_SENTENCE_LENGTH, 2),
                 dtype='int32')
attention_weighted_sentences = TimeDistributed(temp)(texts_in)
# modified just like below, still error
# attention_weighted_sentences = TimeDistributed(bert_model)(texts_in)

model = Model(texts_in, attention_weighted_sentences)
model.summary()



Traceback (most recent call last):
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/phoenixkiller/source/hnatt_bert_keras/error.py", line 29, in <module>
    attention_weighted_sentences = TimeDistributed(temp)(texts_in)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/site-packages/keras/layers/wrappers.py", line 248, in call
    y = self.layer.call(inputs, **kwargs)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/site-packages/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/phoenixkiller/anaconda3/envs/tf1.12/lib/python3.6/site-packages/keras/engine/network.py", line 798, in run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("lambda_1/strided_slice:0", shape=(?, 768), dtype=float32)


```

**Comment by CyberZHG** [comment]
`TimeDistributed` takes a layer as its input, not the output (tensor) of a layer.
