### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 3531060969 vs. calculated on the restored bytes 1701788620

### ISSUE THREAD

**Issue by phoenixkillerli** [CyberZHG/keras-bert#25]
### 测试环境
tensorflow1.13.1+python3.6+ubuntu18.04+cuda10.0
### 报错信息如下
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/notebooks/ner.py", line 95, in train
    embedding = BERTEmbedding('./bert', seq_len)
  File "/usr/local/lib/python3.6/dist-packages/kashgari/embeddings/embeddings.py", line 69, in __init__
    self.build(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kashgari/embeddings/embeddings.py", line 301, in build
    seq_len=self.sequence_length)
  File "/usr/local/lib/python3.6/dist-packages/keras_bert/loader.py", line 71, in load_trained_model_from_checkpoint
    loader('bert/encoder/layer_%d/attention/self/value/kernel' % i),
  File "/usr/local/lib/python3.6/dist-packages/keras_bert/loader.py", line 10, in _loader
    return tf.train.load_variable(checkpoint_file, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/checkpoint_utils.py", line 82, in load_variable
    return reader.get_tensor(name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 3531060969 vs. calculated on the restored bytes 1701788620

```

**Comment by CyberZHG** [comment]
I wasn't able to reproduce the error. And the last croned-CI showed that it works with Tensorflow 1.31.1:

https://travis-ci.org/CyberZHG/keras-bert/jobs/502926428

**Comment by Frank17** [comment]
I have the same issue with tensorflow v1.13.1. @CyberZHG 

Stacktrace:

```
2019-11-14 20:45:50.798762: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "/Users/frank/PycharmProjects/new-classify/src/model.py", line 99, in <module>
    trainable=False
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/keras_bert/loader.py", line 170, in load_trained_model_from_checkpoint
    load_model_weights_from_checkpoint(model, config, checkpoint_file, training=training)
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/keras_bert/loader.py", line 98, in load_model_weights_from_checkpoint
    loader('bert/encoder/layer_%d/attention/self/query/kernel' % i),
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/keras_bert/loader.py", line 18, in _loader
    return tf.train.load_variable(checkpoint_file, name)
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/tensorflow/python/training/checkpoint_utils.py", line 82, in load_variable
    return reader.get_tensor(name)
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/Users/frank/PycharmProjects/new-classify/venv/lib/python3.7/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.DataLossError: Checksum does not match: stored 2134402967 vs. calculated on the restored bytes 2095561258
```
