### ISSUE TITLE
Unable to load official pre-trained checkpoint using load_trained_model_from_checkpoint

### ISSUE THREAD

**Issue by Scarlettg** [CyberZHG/keras-bert#5]
When I try to use load_trained_model_from_checkpoint() to load the official BERT-base uncased model (https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip), I get the following error:

`Traceback (most recent call last):
  File "ner_training_code_BERT.py", line 139, in <module>
    model, loss = build_model()
  File "ner_training_code_BERT.py", line 67, in build_model
    bert_model = load_trained_model_from_checkpoint(_bert_config_path, _bert_checkpoint_path, training=False)
  File "/Users/scguo/miniconda3/envs/py36/lib/python3.6/site-packages/keras_bert/loader.py", line 26, in load_trained_model_from_checkpoint
    tf.train.load_variable(checkpoint_file, 'bert/embeddings/word_embeddings'),
  File "/Users/scguo/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 81, in load_variable
    return reader.get_tensor(name)
  File "/Users/scguo/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 334, in get_tensor
    status)
  File "/Users/scguo/miniconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: bert/embeddings/word_embeddings not found in checkpoint file`

Seems like the op names that we're expecting does not match with the official model?

**Comment by CyberZHG** [comment]
I was not able to reproduce the error with the given checkpoint. 

MD5:
```
b14dd4db03c41fd7ec9e2fb0610a4474 uncased_L-12_H-768_A-12_1.zip

57f8025e6f0e7ed9cf2fb9fa6fed0f79 bert_model.ckpt.data-00000-of-00001
c5b9933019001067c99a11d0c133cedd bert_model.ckpt.index
1ae500078214cfd9db4b45014820fc80 bert_model.ckpt.meta
```

**Comment by Scarlettg** [comment]
My package has the same Md5 checksum. I found out that I got the above error because I was trying to load the ckpt.index file. However, when I try to load the ckpt.data file, I get a file format error as below:
```
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /Users/scguo/Documents/smartmd/keras_ner/bert_models/uncased_L-12_H-768_A-12/bert_model.ckpt.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
```
The only solution I found is to make a copy (or symlink) of the ckpt.data file and have the file extension end in ".ckpt" only. Loading the renamed copy will work, but loading the original will result in file format error.

**Comment by CyberZHG** [comment]
You don't need to rename or copy anything. `bert_checkpoint_path` should end with `.ckpt` just like tensorflow's checkpoint loading.

**Comment by aurora314156** [comment]
Hi,
my file structure is: 

load_and_pool.py
-bert
--config.json
--bert_model.ckpt.data-00000-of-00001
--bert_model.ckpt.index
--bert_model.ckpt.meta
--vocab.txt

and try:
python load_and_pool.py bert/config.json bert/ bert/vocab.txt

but it always gets Error:
[ ValueError: Couldn't find 'checkpoint' file or checkpoints is given directory /bert ]

Can give me some example? plz thx.

**Comment by CyberZHG** [comment]
@aurora314156

```
python load_and_pool.py bert/config.json bert/bert_model.ckpt bert/vocab.txt
```

**Comment by aurora314156** [comment]
THX!
