### ISSUE TITLE
Building a model with tf.keras failed

### ISSUE THREAD

**Issue by BrikerMan** [CyberZHG/keras-bert#65]
**Describe the Bug**

Building a model with tf.keras failed

**Version Info**

* [x] I'm using the latest version

**Minimal Codes To Reproduce**

```python
import os
os.environ['TF_KERAS'] = '1'

# checkpoint: https://github.com/CyberZHG/keras-bert/tree/master/tests/test_checkpoint
bert_model = keras_bert.load_trained_model_from_checkpoint(config_path, check_point_path, seq_len=100)
# Works fine
import keras
keras_model = keras.Model(bert_model.inputs, bert_model.output)

# Error
import tensorflow as tf
model = tf.keras.Model(bert_model.inputs, bert_model.output)
```

```log
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 121, in __init__
    super(Model, self).__init__(*args, **kwargs)
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 81, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 227, in _init_graph_network
    self._track_layers(layers)
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 327, in _track_layers
    layer, name='layer-%d' % layer_index, overwrite=True)
  File "/Users/brikerman/Desktop/python/Kashgari/venv/lib/python3.6/site-packages/tensorflow/python/training/checkpointable/base.py", line 688, in _track_checkpointable
    "Checkpointable.") % (type(checkpointable),))
TypeError: Checkpointable._track_checkpointable() passed type <class 'keras.engine.input_layer.InputLayer'>, not a Checkpointable.
```

**Comment by CyberZHG** [comment]
I guess you import keras_bert before the setting of environment variables. 😹

**Comment by BrikerMan** [comment]
I have updated `tf-keras 0.50.0` and uninstalled keras, then it works like magic. It is my bad, using the outdated version. Is that possible to remove keras from `setup.py`.

**Comment by CyberZHG** [comment]
🤔 I don't think you have to uninstall `keras`.
