### ISSUE TITLE
tensorflow2.0 module 'tensorflow' has no attribute 'placeholder

### ISSUE THREAD

**Issue by aaronlyt** [CyberZHG/keras-bert#74]
**Describe the Bug**

**Version Info**

*  I'm using the latest version
* tensorflow 2.0.0-alpha0, python 3.6

**detailed trace infomation**

Traceback (most recent call last):
  File "run_pipeline3.py", line 112, in <module>
    dev_dataset, steps_per_epoch)
  File "run_pipeline3.py", line 57, in build_model_pipeline
    model = LstmCrf(params)
  File "/home/lyt/workspace/ner/experiment_script/../model/lsmtcrf.py", line 36, in LstmCrf
    inputs, output = get_bert_model(params)
  File "/home/lyt/workspace/ner/experiment_script/../model/lsmtcrf.py", line 29, in get_bert_model
    trainable=None, seq_len=SEQ_LEN)
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras_bert/loader.py", line 169, in load_trained_model_from_checkpoint
    seq_len=seq_len,
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras_bert/loader.py", line 55, in build_model_from_config
    output_layer_num=output_layer_num,
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras_bert/bert.py", line 91, in get_model
    inputs = get_inputs(seq_len=seq_len)
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras_bert/layers/inputs.py", line 15, in get_inputs
    ) for name in names]
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras_bert/layers/inputs.py", line 15, in <listcomp>
    ) for name in names]
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras/engine/input_layer.py", line 87, in __init__
    name=self.name)
  File "/home/lyt/miniconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 517, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
AttributeError: module 'tensorflow' has no attribute 'placeholder'

**Comment by CyberZHG** [comment]
Add `TF_KERAS=1` to your environment variables.

**Comment by aaronlyt** [comment]
add it, and tensorflow2.0-beta works, not work for tensorflow2.0-alpha
