### ISSUE TITLE
ValueError: Expected to see 3 array(s)

### ISSUE THREAD

**Issue by xinsu626** [CyberZHG/keras-bert#78]
I was trying to build the following model:

```
def build_model():
    bert = load_trained_model_from_checkpoint(
        config_file=config_file,
        checkpoint_file=checkpoint_file,
        training=True,
        trainable=True,
        seq_len=256)
    bert_in = bert.inputs[:2]  # two input: segment and token
    bert_out = bert.get_layer('NSP-Dense').output
    model_out = Dense(units=1, activation=None)(bert_out)
    model = Model(bert_in, model_out)
    model.compile(optimizer='Adam',
                  metrics=['acc'],
                  loss='mean_squared_error')
    return bert
```

When I tried to fit the model on my data(features are indices and segment list, labels are real value), I got the following ValueError:

```
Traceback (most recent call last):
  File "bert.py", line 85, in <module>
    epochs=10)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_utils.py", line 102, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 3 array(s), but instead got the following list of 2 arrays: [array([[  101,  3287,  2040, ...,     0,     0,     0],
       [  101,  2053,  2047, ...,     0,     0,     0],
       [  101,  3289,  2020, ...,     0,     0,     0],
       ...,
       [  101,  577...

```

**Comment by xinsu626** [comment]
Never mind. I made some silly mistakes.

**Comment by Serbernari** [comment]
@xinsu626 what was the mistakes?
